/**
 * Canonical product seed data for BasketWise V1 testing.
 * ~100 products across 10 grocery categories with StoreProduct mappings
 * for Coles, Woolworths, and Aldi.
 *
 * NOTE: No prices are included — those come from the scrapers.
 */

interface SeedProduct {
  name: string;
  category: string;
  brand: string | null;
  packSize: string;
  unitOfMeasure: string;
}

interface SeedStoreProduct {
  /** Index into SEED_PRODUCTS array */
  productIndex: number;
  /** Store slug: "coles" | "woolworths" | "aldi" */
  storeSlug: string;
  storeSku: string | null;
  storeName: string;
}

// ─── Products ──────────────────────────────────────────────────────────

export const SEED_PRODUCTS: SeedProduct[] = [
  // ── Dairy (10) ─────────────────────────────────────────────────────
  { name: "Full Cream Milk 2L", category: "Dairy", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Full Cream Milk 1L", category: "Dairy", brand: null, packSize: "1L", unitOfMeasure: "per_L" },
  { name: "Light Milk 2L", category: "Dairy", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Tasty Cheese Block 500g", category: "Dairy", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Shredded Mozzarella 500g", category: "Dairy", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Greek Yoghurt 1kg", category: "Dairy", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Vanilla Yoghurt 1kg", category: "Dairy", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Salted Butter 250g", category: "Dairy", brand: null, packSize: "250g", unitOfMeasure: "per_kg" },
  { name: "Unsalted Butter 250g", category: "Dairy", brand: null, packSize: "250g", unitOfMeasure: "per_kg" },
  { name: "Thickened Cream 300mL", category: "Dairy", brand: null, packSize: "300mL", unitOfMeasure: "per_100mL" },

  // ── Bread & Bakery (5) ─────────────────────────────────────────────
  { name: "White Sandwich Bread 700g", category: "Bread & Bakery", brand: null, packSize: "700g", unitOfMeasure: "per_100g" },
  { name: "Wholemeal Sandwich Bread 700g", category: "Bread & Bakery", brand: null, packSize: "700g", unitOfMeasure: "per_100g" },
  { name: "Sourdough Loaf 650g", category: "Bread & Bakery", brand: null, packSize: "650g", unitOfMeasure: "per_100g" },
  { name: "Wraps 8 Pack", category: "Bread & Bakery", brand: null, packSize: "8 Pack", unitOfMeasure: "per_unit" },
  { name: "Burger Buns 6 Pack", category: "Bread & Bakery", brand: null, packSize: "6 Pack", unitOfMeasure: "per_unit" },

  // ── Meat (10) ──────────────────────────────────────────────────────
  { name: "Chicken Breast Fillets 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Chicken Thigh Fillets 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Beef Mince 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Beef Mince 1kg", category: "Meat", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Pork Sausages 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Bacon Rashers 250g", category: "Meat", brand: null, packSize: "250g", unitOfMeasure: "per_kg" },
  { name: "Lamb Loin Chops 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Chicken Drumsticks 1kg", category: "Meat", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Beef Rump Steak 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Pork Mince 500g", category: "Meat", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },

  // ── Fruit & Veg (12) ──────────────────────────────────────────────
  { name: "Bananas 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Royal Gala Apples 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Navel Oranges 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Brushed Potatoes 2kg", category: "Fruit & Veg", brand: null, packSize: "2kg", unitOfMeasure: "per_kg" },
  { name: "Brown Onions 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Truss Tomatoes 500g", category: "Fruit & Veg", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Iceberg Lettuce Each", category: "Fruit & Veg", brand: null, packSize: "1 Each", unitOfMeasure: "per_unit" },
  { name: "Carrots 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Broccoli Each", category: "Fruit & Veg", brand: null, packSize: "1 Each", unitOfMeasure: "per_unit" },
  { name: "Cucumber Each", category: "Fruit & Veg", brand: null, packSize: "1 Each", unitOfMeasure: "per_unit" },
  { name: "Sweet Potato 1kg", category: "Fruit & Veg", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Avocado Each", category: "Fruit & Veg", brand: null, packSize: "1 Each", unitOfMeasure: "per_unit" },

  // ── Pantry (15) ────────────────────────────────────────────────────
  { name: "Penne Pasta 500g", category: "Pantry", brand: null, packSize: "500g", unitOfMeasure: "per_100g" },
  { name: "Spaghetti 500g", category: "Pantry", brand: null, packSize: "500g", unitOfMeasure: "per_100g" },
  { name: "Basmati Rice 1kg", category: "Pantry", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Long Grain White Rice 2kg", category: "Pantry", brand: null, packSize: "2kg", unitOfMeasure: "per_kg" },
  { name: "Weet-Bix Breakfast Cereal 575g", category: "Pantry", brand: "Sanitarium", packSize: "575g", unitOfMeasure: "per_100g" },
  { name: "Rolled Oats 1kg", category: "Pantry", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Plain Flour 1kg", category: "Pantry", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Self Raising Flour 1kg", category: "Pantry", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "White Sugar 1kg", category: "Pantry", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Canola Oil 750mL", category: "Pantry", brand: null, packSize: "750mL", unitOfMeasure: "per_L" },
  { name: "Extra Virgin Olive Oil 500mL", category: "Pantry", brand: null, packSize: "500mL", unitOfMeasure: "per_L" },
  { name: "Diced Tomatoes 400g", category: "Pantry", brand: null, packSize: "400g", unitOfMeasure: "per_100g" },
  { name: "Baked Beans 420g", category: "Pantry", brand: null, packSize: "420g", unitOfMeasure: "per_100g" },
  { name: "Vegemite 380g", category: "Pantry", brand: "Kraft", packSize: "380g", unitOfMeasure: "per_100g" },
  { name: "Peanut Butter Smooth 375g", category: "Pantry", brand: null, packSize: "375g", unitOfMeasure: "per_100g" },

  // ── Drinks (10) ────────────────────────────────────────────────────
  { name: "Orange Juice 2L", category: "Drinks", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Apple Juice 2L", category: "Drinks", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Coca-Cola 1.25L", category: "Drinks", brand: "Coca-Cola", packSize: "1.25L", unitOfMeasure: "per_L" },
  { name: "Coca-Cola 24 Pack Cans", category: "Drinks", brand: "Coca-Cola", packSize: "24 x 375mL", unitOfMeasure: "per_L" },
  { name: "Spring Water 24 Pack", category: "Drinks", brand: null, packSize: "24 x 600mL", unitOfMeasure: "per_L" },
  { name: "Instant Coffee 200g", category: "Drinks", brand: null, packSize: "200g", unitOfMeasure: "per_100g" },
  { name: "English Breakfast Tea 100 Pack", category: "Drinks", brand: null, packSize: "100 Pack", unitOfMeasure: "per_unit" },
  { name: "Oat Milk 1L", category: "Drinks", brand: null, packSize: "1L", unitOfMeasure: "per_L" },
  { name: "Sparkling Water 1.25L", category: "Drinks", brand: null, packSize: "1.25L", unitOfMeasure: "per_L" },
  { name: "Cordial Lemon 1L", category: "Drinks", brand: null, packSize: "1L", unitOfMeasure: "per_L" },

  // ── Snacks (10) ────────────────────────────────────────────────────
  { name: "Original Chips 175g", category: "Snacks", brand: "Smith's", packSize: "175g", unitOfMeasure: "per_100g" },
  { name: "Salt & Vinegar Chips 175g", category: "Snacks", brand: "Smith's", packSize: "175g", unitOfMeasure: "per_100g" },
  { name: "Dairy Milk Chocolate Block 180g", category: "Snacks", brand: "Cadbury", packSize: "180g", unitOfMeasure: "per_100g" },
  { name: "Tim Tams Original 200g", category: "Snacks", brand: "Arnott's", packSize: "200g", unitOfMeasure: "per_100g" },
  { name: "Scotch Finger Biscuits 250g", category: "Snacks", brand: "Arnott's", packSize: "250g", unitOfMeasure: "per_100g" },
  { name: "Salted Cashews 400g", category: "Snacks", brand: null, packSize: "400g", unitOfMeasure: "per_100g" },
  { name: "Natural Almonds 400g", category: "Snacks", brand: null, packSize: "400g", unitOfMeasure: "per_100g" },
  { name: "Corn Chips 230g", category: "Snacks", brand: "Doritos", packSize: "230g", unitOfMeasure: "per_100g" },
  { name: "Rice Crackers 100g", category: "Snacks", brand: null, packSize: "100g", unitOfMeasure: "per_100g" },
  { name: "Trail Mix 400g", category: "Snacks", brand: null, packSize: "400g", unitOfMeasure: "per_100g" },

  // ── Frozen (10) ────────────────────────────────────────────────────
  { name: "Frozen Mixed Vegetables 1kg", category: "Frozen", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Frozen Peas 1kg", category: "Frozen", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Frozen Corn Kernels 500g", category: "Frozen", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Vanilla Ice Cream 2L", category: "Frozen", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Frozen Margherita Pizza 500g", category: "Frozen", brand: null, packSize: "500g", unitOfMeasure: "per_100g" },
  { name: "Fish Fingers 375g", category: "Frozen", brand: null, packSize: "375g", unitOfMeasure: "per_100g" },
  { name: "Frozen Chicken Nuggets 1kg", category: "Frozen", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Frozen Chips 1kg", category: "Frozen", brand: null, packSize: "1kg", unitOfMeasure: "per_kg" },
  { name: "Frozen Prawns 500g", category: "Frozen", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },
  { name: "Frozen Spinach 500g", category: "Frozen", brand: null, packSize: "500g", unitOfMeasure: "per_kg" },

  // ── Cleaning (10) ─────────────────────────────────────────────────
  { name: "Dishwashing Liquid 500mL", category: "Cleaning", brand: null, packSize: "500mL", unitOfMeasure: "per_100mL" },
  { name: "Laundry Liquid 2L", category: "Cleaning", brand: null, packSize: "2L", unitOfMeasure: "per_L" },
  { name: "Laundry Powder 2kg", category: "Cleaning", brand: null, packSize: "2kg", unitOfMeasure: "per_kg" },
  { name: "Paper Towels 3 Pack", category: "Cleaning", brand: null, packSize: "3 Pack", unitOfMeasure: "per_unit" },
  { name: "Toilet Paper 12 Pack", category: "Cleaning", brand: null, packSize: "12 Pack", unitOfMeasure: "per_unit" },
  { name: "Toilet Paper 24 Pack", category: "Cleaning", brand: null, packSize: "24 Pack", unitOfMeasure: "per_unit" },
  { name: "Surface Spray 500mL", category: "Cleaning", brand: null, packSize: "500mL", unitOfMeasure: "per_100mL" },
  { name: "Dishwasher Tablets 30 Pack", category: "Cleaning", brand: null, packSize: "30 Pack", unitOfMeasure: "per_unit" },
  { name: "Bin Liners 50 Pack", category: "Cleaning", brand: null, packSize: "50 Pack", unitOfMeasure: "per_unit" },
  { name: "Sponges 5 Pack", category: "Cleaning", brand: null, packSize: "5 Pack", unitOfMeasure: "per_unit" },

  // ── Baby & Personal (8) ───────────────────────────────────────────
  { name: "Nappies Crawler 56 Pack", category: "Baby & Personal", brand: null, packSize: "56 Pack", unitOfMeasure: "per_unit" },
  { name: "Baby Wipes 80 Pack", category: "Baby & Personal", brand: null, packSize: "80 Pack", unitOfMeasure: "per_unit" },
  { name: "Shampoo 500mL", category: "Baby & Personal", brand: null, packSize: "500mL", unitOfMeasure: "per_100mL" },
  { name: "Conditioner 500mL", category: "Baby & Personal", brand: null, packSize: "500mL", unitOfMeasure: "per_100mL" },
  { name: "Toothpaste 110g", category: "Baby & Personal", brand: null, packSize: "110g", unitOfMeasure: "per_100g" },
  { name: "Deodorant Roll On 50mL", category: "Baby & Personal", brand: null, packSize: "50mL", unitOfMeasure: "per_100mL" },
  { name: "Sunscreen SPF50+ 200mL", category: "Baby & Personal", brand: null, packSize: "200mL", unitOfMeasure: "per_100mL" },
  { name: "Tissues 200 Pack", category: "Baby & Personal", brand: null, packSize: "200 Pack", unitOfMeasure: "per_unit" },
];

// ─── Store Product Mappings ────────────────────────────────────────────

/**
 * Helper to create store product entries for all 3 stores for a given product.
 * Aldi SKUs are null (TBD). Coles SKUs are 6-digit, Woolworths are 6-digit article IDs.
 */
function mapAllStores(
  productIndex: number,
  coles: { sku: string; name: string },
  woolworths: { sku: string; name: string },
  aldi: { name: string },
): SeedStoreProduct[] {
  return [
    { productIndex, storeSlug: "coles", storeSku: coles.sku, storeName: coles.name },
    { productIndex, storeSlug: "woolworths", storeSku: woolworths.sku, storeName: woolworths.name },
    { productIndex, storeSlug: "aldi", storeSku: null, storeName: aldi.name },
  ];
}

export const SEED_STORE_PRODUCTS: SeedStoreProduct[] = [
  // ── Dairy ──────────────────────────────────────────────────────────
  ...mapAllStores(0,
    { sku: "100201", name: "Coles Full Cream Milk 2L" },
    { sku: "800123", name: "Woolworths Full Cream Milk 2L" },
    { name: "Farmdale Full Cream Milk 2L" },
  ),
  ...mapAllStores(1,
    { sku: "100202", name: "Coles Full Cream Milk 1L" },
    { sku: "800124", name: "Woolworths Full Cream Milk 1L" },
    { name: "Farmdale Full Cream Milk 1L" },
  ),
  ...mapAllStores(2,
    { sku: "100210", name: "Coles Light Milk 2L" },
    { sku: "800130", name: "Woolworths Light Milk 2L" },
    { name: "Farmdale Light Milk 2L" },
  ),
  ...mapAllStores(3,
    { sku: "100310", name: "Coles Tasty Cheese Block 500g" },
    { sku: "800210", name: "Woolworths Tasty Cheese Block 500g" },
    { name: "Westacre Tasty Cheese Block 500g" },
  ),
  ...mapAllStores(4,
    { sku: "100320", name: "Coles Shredded Mozzarella 500g" },
    { sku: "800220", name: "Woolworths Shredded Mozzarella 500g" },
    { name: "Westacre Shredded Mozzarella 500g" },
  ),
  ...mapAllStores(5,
    { sku: "100410", name: "Coles Greek Yoghurt 1kg" },
    { sku: "800310", name: "Woolworths Greek Yoghurt 1kg" },
    { name: "Dairy Dream Greek Yoghurt 1kg" },
  ),
  ...mapAllStores(6,
    { sku: "100420", name: "Coles Vanilla Yoghurt 1kg" },
    { sku: "800320", name: "Woolworths Vanilla Yoghurt 1kg" },
    { name: "Dairy Dream Vanilla Yoghurt 1kg" },
  ),
  ...mapAllStores(7,
    { sku: "100510", name: "Coles Salted Butter 250g" },
    { sku: "800410", name: "Woolworths Salted Butter 250g" },
    { name: "Beautifully Butterfully Salted Butter 250g" },
  ),
  ...mapAllStores(8,
    { sku: "100520", name: "Coles Unsalted Butter 250g" },
    { sku: "800420", name: "Woolworths Unsalted Butter 250g" },
    { name: "Beautifully Butterfully Unsalted Butter 250g" },
  ),
  ...mapAllStores(9,
    { sku: "100610", name: "Coles Thickened Cream 300mL" },
    { sku: "800510", name: "Woolworths Thickened Cream 300mL" },
    { name: "Farmdale Thickened Cream 300mL" },
  ),

  // ── Bread & Bakery ─────────────────────────────────────────────────
  ...mapAllStores(10,
    { sku: "200101", name: "Coles White Sandwich Bread 700g" },
    { sku: "810101", name: "Woolworths White Sandwich Bread 700g" },
    { name: "Baker's Life White Sandwich Bread 700g" },
  ),
  ...mapAllStores(11,
    { sku: "200102", name: "Coles Wholemeal Sandwich Bread 700g" },
    { sku: "810102", name: "Woolworths Wholemeal Sandwich Bread 700g" },
    { name: "Baker's Life Wholemeal Sandwich Bread 700g" },
  ),
  ...mapAllStores(12,
    { sku: "200110", name: "Coles Sourdough Loaf 650g" },
    { sku: "810110", name: "Woolworths Sourdough Loaf 650g" },
    { name: "Baker's Life Sourdough Loaf 650g" },
  ),
  ...mapAllStores(13,
    { sku: "200201", name: "Coles Wraps 8 Pack" },
    { sku: "810201", name: "Woolworths Wraps 8 Pack" },
    { name: "Baker's Life Wraps 8 Pack" },
  ),
  ...mapAllStores(14,
    { sku: "200301", name: "Coles Burger Buns 6 Pack" },
    { sku: "810301", name: "Woolworths Burger Buns 6 Pack" },
    { name: "Baker's Life Burger Buns 6 Pack" },
  ),

  // ── Meat ───────────────────────────────────────────────────────────
  ...mapAllStores(15,
    { sku: "300101", name: "Coles RSPCA Chicken Breast Fillets 500g" },
    { sku: "820101", name: "Woolworths Free Range Chicken Breast 500g" },
    { name: "Ashdale Chicken Breast Fillets 500g" },
  ),
  ...mapAllStores(16,
    { sku: "300102", name: "Coles RSPCA Chicken Thigh Fillets 500g" },
    { sku: "820102", name: "Woolworths Free Range Chicken Thigh 500g" },
    { name: "Ashdale Chicken Thigh Fillets 500g" },
  ),
  ...mapAllStores(17,
    { sku: "300201", name: "Coles 3 Star Beef Mince 500g" },
    { sku: "820201", name: "Woolworths Beef Mince 500g" },
    { name: "Ashdale Beef Mince 500g" },
  ),
  ...mapAllStores(18,
    { sku: "300202", name: "Coles 3 Star Beef Mince 1kg" },
    { sku: "820202", name: "Woolworths Beef Mince 1kg" },
    { name: "Ashdale Beef Mince 1kg" },
  ),
  ...mapAllStores(19,
    { sku: "300301", name: "Coles Pork Sausages 500g" },
    { sku: "820301", name: "Woolworths Pork Sausages 500g" },
    { name: "Ashdale Pork Sausages 500g" },
  ),
  ...mapAllStores(20,
    { sku: "300401", name: "Coles Rindless Bacon Rashers 250g" },
    { sku: "820401", name: "Woolworths Shortcut Bacon 250g" },
    { name: "Berg Bacon Rashers 250g" },
  ),
  ...mapAllStores(21,
    { sku: "300501", name: "Coles Lamb Loin Chops 500g" },
    { sku: "820501", name: "Woolworths Lamb Loin Chops 500g" },
    { name: "Ashdale Lamb Loin Chops 500g" },
  ),
  ...mapAllStores(22,
    { sku: "300601", name: "Coles Chicken Drumsticks 1kg" },
    { sku: "820601", name: "Woolworths Chicken Drumsticks 1kg" },
    { name: "Ashdale Chicken Drumsticks 1kg" },
  ),
  ...mapAllStores(23,
    { sku: "300701", name: "Coles Beef Rump Steak 500g" },
    { sku: "820701", name: "Woolworths Beef Rump Steak 500g" },
    { name: "Ashdale Beef Rump Steak 500g" },
  ),
  ...mapAllStores(24,
    { sku: "300801", name: "Coles Pork Mince 500g" },
    { sku: "820801", name: "Woolworths Pork Mince 500g" },
    { name: "Ashdale Pork Mince 500g" },
  ),

  // ── Fruit & Veg ───────────────────────────────────────────────────
  ...mapAllStores(25,
    { sku: "400101", name: "Coles Bananas per kg" },
    { sku: "830101", name: "Woolworths Bananas per kg" },
    { name: "Bananas per kg" },
  ),
  ...mapAllStores(26,
    { sku: "400201", name: "Coles Royal Gala Apples per kg" },
    { sku: "830201", name: "Woolworths Royal Gala Apples per kg" },
    { name: "Royal Gala Apples per kg" },
  ),
  ...mapAllStores(27,
    { sku: "400301", name: "Coles Navel Oranges per kg" },
    { sku: "830301", name: "Woolworths Navel Oranges per kg" },
    { name: "Navel Oranges per kg" },
  ),
  ...mapAllStores(28,
    { sku: "400401", name: "Coles Brushed Potatoes 2kg" },
    { sku: "830401", name: "Woolworths Brushed Potatoes 2kg" },
    { name: "Brushed Potatoes 2kg" },
  ),
  ...mapAllStores(29,
    { sku: "400501", name: "Coles Brown Onions 1kg" },
    { sku: "830501", name: "Woolworths Brown Onions 1kg" },
    { name: "Brown Onions 1kg" },
  ),
  ...mapAllStores(30,
    { sku: "400601", name: "Coles Truss Tomatoes 500g" },
    { sku: "830601", name: "Woolworths Truss Tomatoes 500g" },
    { name: "Truss Tomatoes 500g" },
  ),
  ...mapAllStores(31,
    { sku: "400701", name: "Coles Iceberg Lettuce Each" },
    { sku: "830701", name: "Woolworths Iceberg Lettuce Each" },
    { name: "Iceberg Lettuce Each" },
  ),
  ...mapAllStores(32,
    { sku: "400801", name: "Coles Carrots 1kg" },
    { sku: "830801", name: "Woolworths Carrots 1kg" },
    { name: "Carrots 1kg" },
  ),
  ...mapAllStores(33,
    { sku: "400901", name: "Coles Broccoli Each" },
    { sku: "830901", name: "Woolworths Broccoli Each" },
    { name: "Broccoli Each" },
  ),
  ...mapAllStores(34,
    { sku: "401001", name: "Coles Cucumber Each" },
    { sku: "831001", name: "Woolworths Cucumber Each" },
    { name: "Cucumber Each" },
  ),
  ...mapAllStores(35,
    { sku: "401101", name: "Coles Sweet Potato per kg" },
    { sku: "831101", name: "Woolworths Sweet Potato per kg" },
    { name: "Sweet Potato per kg" },
  ),
  ...mapAllStores(36,
    { sku: "401201", name: "Coles Avocado Each" },
    { sku: "831201", name: "Woolworths Avocado Each" },
    { name: "Avocado Each" },
  ),

  // ── Pantry ─────────────────────────────────────────────────────────
  ...mapAllStores(37,
    { sku: "500101", name: "Coles Penne Pasta 500g" },
    { sku: "840101", name: "Woolworths Penne Pasta 500g" },
    { name: "Remano Penne Pasta 500g" },
  ),
  ...mapAllStores(38,
    { sku: "500102", name: "Coles Spaghetti 500g" },
    { sku: "840102", name: "Woolworths Spaghetti 500g" },
    { name: "Remano Spaghetti 500g" },
  ),
  ...mapAllStores(39,
    { sku: "500201", name: "Coles Basmati Rice 1kg" },
    { sku: "840201", name: "Woolworths Basmati Rice 1kg" },
    { name: "Domus Basmati Rice 1kg" },
  ),
  ...mapAllStores(40,
    { sku: "500202", name: "Coles Long Grain White Rice 2kg" },
    { sku: "840202", name: "Woolworths Long Grain White Rice 2kg" },
    { name: "Domus Long Grain White Rice 2kg" },
  ),
  ...mapAllStores(41,
    { sku: "500301", name: "Sanitarium Weet-Bix 575g" },
    { sku: "840301", name: "Sanitarium Weet-Bix 575g" },
    { name: "Sanitarium Weet-Bix 575g" },
  ),
  ...mapAllStores(42,
    { sku: "500302", name: "Coles Rolled Oats 1kg" },
    { sku: "840302", name: "Woolworths Rolled Oats 1kg" },
    { name: "Brooklea Rolled Oats 1kg" },
  ),
  ...mapAllStores(43,
    { sku: "500401", name: "Coles Plain Flour 1kg" },
    { sku: "840401", name: "Woolworths Plain Flour 1kg" },
    { name: "Baker's Life Plain Flour 1kg" },
  ),
  ...mapAllStores(44,
    { sku: "500402", name: "Coles Self Raising Flour 1kg" },
    { sku: "840402", name: "Woolworths Self Raising Flour 1kg" },
    { name: "Baker's Life Self Raising Flour 1kg" },
  ),
  ...mapAllStores(45,
    { sku: "500501", name: "Coles White Sugar 1kg" },
    { sku: "840501", name: "Woolworths White Sugar 1kg" },
    { name: "Bramwells White Sugar 1kg" },
  ),
  ...mapAllStores(46,
    { sku: "500601", name: "Coles Canola Oil 750mL" },
    { sku: "840601", name: "Woolworths Canola Oil 750mL" },
    { name: "Remano Canola Oil 750mL" },
  ),
  ...mapAllStores(47,
    { sku: "500602", name: "Coles Extra Virgin Olive Oil 500mL" },
    { sku: "840602", name: "Woolworths Extra Virgin Olive Oil 500mL" },
    { name: "Remano Extra Virgin Olive Oil 500mL" },
  ),
  ...mapAllStores(48,
    { sku: "500701", name: "Coles Diced Tomatoes 400g" },
    { sku: "840701", name: "Woolworths Diced Tomatoes 400g" },
    { name: "Remano Diced Tomatoes 400g" },
  ),
  ...mapAllStores(49,
    { sku: "500801", name: "Coles Baked Beans 420g" },
    { sku: "840801", name: "Woolworths Baked Beans 420g" },
    { name: "Bramwells Baked Beans 420g" },
  ),
  ...mapAllStores(50,
    { sku: "500901", name: "Kraft Vegemite 380g" },
    { sku: "840901", name: "Kraft Vegemite 380g" },
    { name: "Kraft Vegemite 380g" },
  ),
  ...mapAllStores(51,
    { sku: "501001", name: "Coles Peanut Butter Smooth 375g" },
    { sku: "841001", name: "Woolworths Peanut Butter Smooth 375g" },
    { name: "Bramwells Peanut Butter Smooth 375g" },
  ),

  // ── Drinks ─────────────────────────────────────────────────────────
  ...mapAllStores(52,
    { sku: "600101", name: "Coles Orange Juice 2L" },
    { sku: "850101", name: "Woolworths Orange Juice 2L" },
    { name: "Farmdale Orange Juice 2L" },
  ),
  ...mapAllStores(53,
    { sku: "600102", name: "Coles Apple Juice 2L" },
    { sku: "850102", name: "Woolworths Apple Juice 2L" },
    { name: "Farmdale Apple Juice 2L" },
  ),
  ...mapAllStores(54,
    { sku: "600201", name: "Coca-Cola 1.25L" },
    { sku: "850201", name: "Coca-Cola 1.25L" },
    { name: "Coca-Cola 1.25L" },
  ),
  ...mapAllStores(55,
    { sku: "600202", name: "Coca-Cola 24 x 375mL Cans" },
    { sku: "850202", name: "Coca-Cola 24 x 375mL Cans" },
    { name: "Coca-Cola 24 x 375mL Cans" },
  ),
  ...mapAllStores(56,
    { sku: "600301", name: "Coles Spring Water 24 x 600mL" },
    { sku: "850301", name: "Woolworths Spring Water 24 x 600mL" },
    { name: "Quench Spring Water 24 x 600mL" },
  ),
  ...mapAllStores(57,
    { sku: "600401", name: "Coles Instant Coffee 200g" },
    { sku: "850401", name: "Woolworths Instant Coffee 200g" },
    { name: "Alcafe Instant Coffee 200g" },
  ),
  ...mapAllStores(58,
    { sku: "600501", name: "Coles English Breakfast Tea 100 Pack" },
    { sku: "850501", name: "Woolworths English Breakfast Tea 100 Pack" },
    { name: "Diplomat English Breakfast Tea 100 Pack" },
  ),
  ...mapAllStores(59,
    { sku: "600601", name: "Coles Oat Milk 1L" },
    { sku: "850601", name: "Woolworths Oat Milk 1L" },
    { name: "Just Organic Oat Milk 1L" },
  ),
  ...mapAllStores(60,
    { sku: "600701", name: "Coles Sparkling Water 1.25L" },
    { sku: "850701", name: "Woolworths Sparkling Water 1.25L" },
    { name: "Quench Sparkling Water 1.25L" },
  ),
  ...mapAllStores(61,
    { sku: "600801", name: "Coles Lemon Cordial 1L" },
    { sku: "850801", name: "Woolworths Lemon Cordial 1L" },
    { name: "Grandessa Lemon Cordial 1L" },
  ),

  // ── Snacks ─────────────────────────────────────────────────────────
  ...mapAllStores(62,
    { sku: "700101", name: "Smith's Original Chips 175g" },
    { sku: "860101", name: "Smith's Original Chips 175g" },
    { name: "Clancy's Original Chips 175g" },
  ),
  ...mapAllStores(63,
    { sku: "700102", name: "Smith's Salt & Vinegar Chips 175g" },
    { sku: "860102", name: "Smith's Salt & Vinegar Chips 175g" },
    { name: "Clancy's Salt & Vinegar Chips 175g" },
  ),
  ...mapAllStores(64,
    { sku: "700201", name: "Cadbury Dairy Milk Chocolate 180g" },
    { sku: "860201", name: "Cadbury Dairy Milk Chocolate 180g" },
    { name: "Cadbury Dairy Milk Chocolate 180g" },
  ),
  ...mapAllStores(65,
    { sku: "700301", name: "Arnott's Tim Tams Original 200g" },
    { sku: "860301", name: "Arnott's Tim Tams Original 200g" },
    { name: "Arnott's Tim Tams Original 200g" },
  ),
  ...mapAllStores(66,
    { sku: "700302", name: "Arnott's Scotch Finger 250g" },
    { sku: "860302", name: "Arnott's Scotch Finger 250g" },
    { name: "Arnott's Scotch Finger 250g" },
  ),
  ...mapAllStores(67,
    { sku: "700401", name: "Coles Salted Cashews 400g" },
    { sku: "860401", name: "Woolworths Salted Cashews 400g" },
    { name: "Forresters Salted Cashews 400g" },
  ),
  ...mapAllStores(68,
    { sku: "700402", name: "Coles Natural Almonds 400g" },
    { sku: "860402", name: "Woolworths Natural Almonds 400g" },
    { name: "Forresters Natural Almonds 400g" },
  ),
  ...mapAllStores(69,
    { sku: "700501", name: "Doritos Corn Chips 230g" },
    { sku: "860501", name: "Doritos Corn Chips 230g" },
    { name: "Clancy's Corn Chips 230g" },
  ),
  ...mapAllStores(70,
    { sku: "700601", name: "Coles Rice Crackers 100g" },
    { sku: "860601", name: "Woolworths Rice Crackers 100g" },
    { name: "Forresters Rice Crackers 100g" },
  ),
  ...mapAllStores(71,
    { sku: "700701", name: "Coles Trail Mix 400g" },
    { sku: "860701", name: "Woolworths Trail Mix 400g" },
    { name: "Forresters Trail Mix 400g" },
  ),

  // ── Frozen ─────────────────────────────────────────────────────────
  ...mapAllStores(72,
    { sku: "800101", name: "Coles Frozen Mixed Vegetables 1kg" },
    { sku: "870101", name: "Woolworths Frozen Mixed Vegetables 1kg" },
    { name: "Market Fare Mixed Vegetables 1kg" },
  ),
  ...mapAllStores(73,
    { sku: "800102", name: "Coles Frozen Peas 1kg" },
    { sku: "870102", name: "Woolworths Frozen Peas 1kg" },
    { name: "Market Fare Peas 1kg" },
  ),
  ...mapAllStores(74,
    { sku: "800103", name: "Coles Frozen Corn Kernels 500g" },
    { sku: "870103", name: "Woolworths Frozen Corn Kernels 500g" },
    { name: "Market Fare Corn Kernels 500g" },
  ),
  ...mapAllStores(75,
    { sku: "800201", name: "Coles Vanilla Ice Cream 2L" },
    { sku: "870201", name: "Woolworths Vanilla Ice Cream 2L" },
    { name: "Monarc Vanilla Ice Cream 2L" },
  ),
  ...mapAllStores(76,
    { sku: "800301", name: "Coles Frozen Margherita Pizza 500g" },
    { sku: "870301", name: "Woolworths Frozen Margherita Pizza 500g" },
    { name: "Casa Barelli Margherita Pizza 500g" },
  ),
  ...mapAllStores(77,
    { sku: "800401", name: "Coles Fish Fingers 375g" },
    { sku: "870401", name: "Woolworths Fish Fingers 375g" },
    { name: "Ocean Rise Fish Fingers 375g" },
  ),
  ...mapAllStores(78,
    { sku: "800501", name: "Coles Frozen Chicken Nuggets 1kg" },
    { sku: "870501", name: "Woolworths Frozen Chicken Nuggets 1kg" },
    { name: "Lodge Farm Chicken Nuggets 1kg" },
  ),
  ...mapAllStores(79,
    { sku: "800601", name: "Coles Frozen Chips 1kg" },
    { sku: "870601", name: "Woolworths Frozen Chips 1kg" },
    { name: "Market Fare Chips 1kg" },
  ),
  ...mapAllStores(80,
    { sku: "800701", name: "Coles Frozen Prawns 500g" },
    { sku: "870701", name: "Woolworths Frozen Prawns 500g" },
    { name: "Ocean Rise Frozen Prawns 500g" },
  ),
  ...mapAllStores(81,
    { sku: "800801", name: "Coles Frozen Spinach 500g" },
    { sku: "870801", name: "Woolworths Frozen Spinach 500g" },
    { name: "Market Fare Frozen Spinach 500g" },
  ),

  // ── Cleaning ───────────────────────────────────────────────────────
  ...mapAllStores(82,
    { sku: "900101", name: "Coles Dishwashing Liquid 500mL" },
    { sku: "880101", name: "Woolworths Dishwashing Liquid 500mL" },
    { name: "Tandil Dishwashing Liquid 500mL" },
  ),
  ...mapAllStores(83,
    { sku: "900201", name: "Coles Laundry Liquid 2L" },
    { sku: "880201", name: "Woolworths Laundry Liquid 2L" },
    { name: "Tandil Laundry Liquid 2L" },
  ),
  ...mapAllStores(84,
    { sku: "900202", name: "Coles Laundry Powder 2kg" },
    { sku: "880202", name: "Woolworths Laundry Powder 2kg" },
    { name: "Tandil Laundry Powder 2kg" },
  ),
  ...mapAllStores(85,
    { sku: "900301", name: "Coles Paper Towels 3 Pack" },
    { sku: "880301", name: "Woolworths Paper Towels 3 Pack" },
    { name: "Confidence Paper Towels 3 Pack" },
  ),
  ...mapAllStores(86,
    { sku: "900401", name: "Coles Toilet Paper 12 Pack" },
    { sku: "880401", name: "Woolworths Toilet Paper 12 Pack" },
    { name: "Confidence Toilet Paper 12 Pack" },
  ),
  ...mapAllStores(87,
    { sku: "900402", name: "Coles Toilet Paper 24 Pack" },
    { sku: "880402", name: "Woolworths Toilet Paper 24 Pack" },
    { name: "Confidence Toilet Paper 24 Pack" },
  ),
  ...mapAllStores(88,
    { sku: "900501", name: "Coles Surface Spray 500mL" },
    { sku: "880501", name: "Woolworths Surface Spray 500mL" },
    { name: "Tandil Surface Spray 500mL" },
  ),
  ...mapAllStores(89,
    { sku: "900601", name: "Coles Dishwasher Tablets 30 Pack" },
    { sku: "880601", name: "Woolworths Dishwasher Tablets 30 Pack" },
    { name: "Tandil Dishwasher Tablets 30 Pack" },
  ),
  ...mapAllStores(90,
    { sku: "900701", name: "Coles Bin Liners 50 Pack" },
    { sku: "880701", name: "Woolworths Bin Liners 50 Pack" },
    { name: "Tandil Bin Liners 50 Pack" },
  ),
  ...mapAllStores(91,
    { sku: "900801", name: "Coles Sponges 5 Pack" },
    { sku: "880801", name: "Woolworths Sponges 5 Pack" },
    { name: "Tandil Sponges 5 Pack" },
  ),

  // ── Baby & Personal ───────────────────────────────────────────────
  ...mapAllStores(92,
    { sku: "950101", name: "Coles Nappies Crawler 56 Pack" },
    { sku: "890101", name: "Woolworths Nappies Crawler 56 Pack" },
    { name: "Mamia Nappies Crawler 56 Pack" },
  ),
  ...mapAllStores(93,
    { sku: "950102", name: "Coles Baby Wipes 80 Pack" },
    { sku: "890102", name: "Woolworths Baby Wipes 80 Pack" },
    { name: "Mamia Baby Wipes 80 Pack" },
  ),
  ...mapAllStores(94,
    { sku: "950201", name: "Coles Shampoo 500mL" },
    { sku: "890201", name: "Woolworths Shampoo 500mL" },
    { name: "Protane Shampoo 500mL" },
  ),
  ...mapAllStores(95,
    { sku: "950202", name: "Coles Conditioner 500mL" },
    { sku: "890202", name: "Woolworths Conditioner 500mL" },
    { name: "Protane Conditioner 500mL" },
  ),
  ...mapAllStores(96,
    { sku: "950301", name: "Coles Toothpaste 110g" },
    { sku: "890301", name: "Woolworths Toothpaste 110g" },
    { name: "Dentitex Toothpaste 110g" },
  ),
  ...mapAllStores(97,
    { sku: "950401", name: "Coles Deodorant Roll On 50mL" },
    { sku: "890401", name: "Woolworths Deodorant Roll On 50mL" },
    { name: "Lacura Deodorant Roll On 50mL" },
  ),
  ...mapAllStores(98,
    { sku: "950501", name: "Coles Sunscreen SPF50+ 200mL" },
    { sku: "890501", name: "Woolworths Sunscreen SPF50+ 200mL" },
    { name: "Ombra Sunscreen SPF50+ 200mL" },
  ),
  ...mapAllStores(99,
    { sku: "950601", name: "Coles Tissues 200 Pack" },
    { sku: "890601", name: "Woolworths Tissues 200 Pack" },
    { name: "Confidence Tissues 200 Pack" },
  ),
];
